### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by gamerplaceorigin** [pythobotmaker/craigslist#2]
Hello, so basically I did all the steps (installed selenium installed requirements.txt + pip install webdriver-manager && pip install webdriver_manager) and won't work with python 3.10.x and latest version of chrome on windows 10 x64 and windows 7 x64 and x86. I receive the error `Traceback (most recent call last):
  File "C:\Users\Bael\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Bael\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Bael\Desktop\craigslist-main\CLBotPhone.py", line 6, in <module>
    from webdriver_manager import driver
ModuleNotFoundError: No module named 'webdriver_manager'`

**Comment by Code-Wizard-py-js** [comment]
pip install webdriver_manager

**Comment by Code-Wizard-py-js** [comment]
updated
